---
http-url: "http://host.docker.internal:8980/opennms"
broker-url: "failover:tcp://host.docker.internal:61616"
id: "minion-app1"
location: "minion-app1-location"

karaf:
  shell:
    ssh:
      host: "0.0.0.0"

netmgt:
  syslog:
    syslog.listen.interface: "0.0.0.0"
    syslog.listen.port: 1514

  traps:
    trapd.listen.interface: "0.0.0.0"
    trapd.listen.port: 1162
